const $=s=>document.querySelector(s);let backend=localStorage.getItem('backend')||'http://127.0.0.1:8000';let speak=localStorage.getItem('speak')!=='false';let history=[];
function bubble(t,c){let d=document.createElement('div');d.className='bubble '+c;d.textContent=t;$('#chat').appendChild(d);$('#chat').scrollTop=$('#chat').scrollHeight}
function say(t){if(!speak||!speechSynthesis)return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='ms-MY';u.rate=.95;speechSynthesis.speak(u)}
async function send(t){t=t.trim();if(!t)return;bubble(t,'you');history.push({role:'user',content:t});$('#input').value='';try{let r=await fetch(backend+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,history})});let j=await r.json();bubble(j.reply,'mak');history.push({role:'assistant',content:j.reply});say(j.reply)}catch(e){bubble('Local demo: backend tak connect lagi. Start FastAPI dulu naa 😘','mak')}}
$('#send').onclick=()=>send($('#input').value);$('#input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send($('#input').value)}};document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>send(b.dataset.q));
let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){let r=new SR();r.lang='ms-MY';r.onstart=()=>$('#mic').textContent='🔴 Listening...';r.onend=()=>$('#mic').textContent='🎙️ Hold to talk';r.onresult=e=>send(e.results[0][0].transcript);$('#mic').onmousedown=()=>{try{r.start()}catch{}}}else $('#mic').onclick=()=>alert('Try Chrome or Edge for speech recognition.');
$('#settings').onclick=async()=>{$('#url').value=backend;$('#speak').checked=speak;await loadMem();$('#dlg').showModal()};$('#close').onclick=()=>$('#dlg').close();$('#save').onclick=()=>{backend=$('#url').value.replace(/\/$/,'');speak=$('#speak').checked;localStorage.setItem('backend',backend);localStorage.setItem('speak',speak);$('#dlg').close()};
async function loadMem(){try{let j=await (await fetch(backend+'/api/memory')).json();$('#mem').innerHTML=j.items.map(x=>`<div>${esc(x.text)} <button onclick="del('${x.id}')">×</button></div>`).join('')||'<small>No memories.</small>'}catch{$('#mem').textContent='Backend unavailable.'}}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
window.del=async id=>{await fetch(backend+'/api/memory/'+id,{method:'DELETE'});loadMem()};$('#add').onclick=async()=>{let t=$('#memtxt').value.trim();if(!t)return;await fetch(backend+'/api/memory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:t})});$('#memtxt').value='';loadMem()};
bubble('Ok minnn 😘 Cerita kat mak, pa jadi ni?','mak');
